### PR TITLE
Features

### PR DESCRIPTION
**Pull request by nikasulo**
# Description
A simple book library built with Vanilla JS(ES6). It allows you add books to your library, delete them
and mark them as either read or unread.

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
# Changes required 🙂 

### Great job so far. Here are some pointers to get you a thumb up on this project.

- Add stickler to your project and ensure your code is passing the linter check.
- Add a descriptive README.md file to this project.
- [**optional**] Your form should be hidden and cleared after each submission of the book.
- Remove all files you don't need from the project

Request for a re-review when you're done.

**James Okunlade**
Happy coding! 😎

**Review by BalintMendli — APPROVED** [review]
Hi @Oluwadamilareolusakin ,

Great job implementing requested changes.

It is a 
### 👍 

But please add a more descriptive readme before merging.

**Comment by nikasulo** [comment]
@zenott hey man, thanks for the thumbs up 😊. If you don't mind, can you point out some of the things that should go in the readme? It's a pretty basic project with nothing to really setup so I'm not sure what else I can add to the readme

**Comment by BalintMendli** [comment]
> @zenott hey man, thanks for the thumbs up 😊. If you don't mind, can you point out some of the things that should go in the readme? It's a pretty basic project with nothing to really setup so I'm not sure what else I can add to the readme

@Oluwadamilareolusakin , there's a readme template which will be available soon to students, you can take a look on it and apply what is relevant to your project: https://gist.github.com/zenott/61ff835815ae5d73c825895f6b70ff64

**Comment by nikasulo** [comment]
@zenott many thanks 😊.

**Pull request merged**
